language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

stages:
  - analyze
  - test

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.6
      dist: xenial
    - php: 5.5
      dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache
    - build/cache

install:
  - phpenv config-rm xdebug.ini || true
  - composer remove --no-update --dev friendsofphp/php-cs-fixer
  - if [[ $TRAVIS_PHP_VERSION = nightly ]]; then export COMPOSER_FLAGS="--ignore-platform-reqs"; fi
  - travis_retry composer install --prefer-dist $COMPOSER_FLAGS

script:
  - php vendor/bin/phpunit --repeat=2
